<?= $this->doctype() ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('PokeAPI - Laminas')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <a class="navbar-brand" href="<?= $this->url('home') ?>">
                    <img src="<?= $this->basePath('img/pokeapi_logo.png') ?>" alt="Laminas">
                    <span class="navbar-text text-light">Prueba técnica</span>
                </a>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p> &copy; <?= date('Y') ?> Jader Sánchez - Prueba ténica productos eterna</p>
            </footer>
        </div>
        <?= $this->inlineScript()->prependFile($this->basePath('js/bootstrap.min.js')) ?>
        <?= $this->inlineScript()->prependFile($this->basePath('js/app.js')) ?>

    </body>
</html>
